"""
Centralized Constants for Construction Intelligence Hub (CIH) Backend.
"""

# User Roles
ROLE_ADMIN = "ADMIN"
ROLE_PROJECT_MANAGER = "PROJECT_MANAGER"
ROLE_SITE_ENGINEER = "SITE_ENGINEER"
ROLE_SAFETY_OFFICER = "SAFETY_OFFICER"
ROLE_ESTIMATOR = "ESTIMATOR"
ROLE_VIEWER = "VIEWER"

USER_ROLES = [
    ROLE_ADMIN,
    ROLE_PROJECT_MANAGER,
    ROLE_SITE_ENGINEER,
    ROLE_SAFETY_OFFICER,
    ROLE_ESTIMATOR,
    ROLE_VIEWER,
]

# User Status
STATUS_ACTIVE = "ACTIVE"
STATUS_INACTIVE = "INACTIVE"
STATUS_SUSPENDED = "SUSPENDED"

# Project Status
PROJECT_STATUS_PLANNED = "PLANNED"
PROJECT_STATUS_IN_PROGRESS = "IN_PROGRESS"
PROJECT_STATUS_ON_HOLD = "ON_HOLD"
PROJECT_STATUS_COMPLETED = "COMPLETED"
PROJECT_STATUS_CANCELLED = "CANCELLED"

# Risk Levels
RISK_LOW = "LOW"
RISK_MEDIUM = "MEDIUM"
RISK_HIGH = "HIGH"
RISK_CRITICAL = "CRITICAL"

# Report Types
REPORT_SUMMARY = "SUMMARY"
REPORT_COST = "COST"
REPORT_MATERIAL = "MATERIAL"
REPORT_WORKER = "WORKER"
REPORT_EQUIPMENT = "EQUIPMENT"
REPORT_SAFETY = "SAFETY"
REPORT_PROGRESS = "PROGRESS"

# Defaults
DEFAULT_CURRENCY = "USD"
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
