"""PDF and Excel report generation for Construction Intelligence Hub."""
from __future__ import annotations

import io
from datetime import datetime
from typing import Iterable

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, PageBreak,
)

from utils import format_currency, format_number

PRIMARY = colors.HexColor("#1E4FD8")
ACCENT = colors.HexColor("#F26A21")
LIGHT = colors.HexColor("#F0F4FF")
DARK = colors.HexColor("#0F1E3D")


# --------------------------------------------------------------------------- #
# helpers
# --------------------------------------------------------------------------- #
def _styles():
    ss = getSampleStyleSheet()
    ss.add(ParagraphStyle(
        name="CIHTitle", parent=ss["Title"], fontName="Helvetica-Bold",
        fontSize=20, textColor=DARK, spaceAfter=6,
    ))
    ss.add(ParagraphStyle(
        name="CIHSub", parent=ss["Normal"], fontSize=10,
        textColor=colors.HexColor("#5A6B8C"), spaceAfter=10,
    ))
    ss.add(ParagraphStyle(
        name="CIHH2", parent=ss["Heading2"], fontName="Helvetica-Bold",
        fontSize=13, textColor=PRIMARY, spaceBefore=10, spaceAfter=6,
    ))
    return ss


def _footer(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.HexColor("#5A6B8C"))
    canvas.drawString(15 * mm, 10 * mm,
                      f"Generated by Construction Intelligence Hub  •  "
                      f"{datetime.now():%Y-%m-%d %H:%M}")
    canvas.drawRightString(200 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _header_block(company: str, subtitle: str, ss) -> list:
    return [
        Paragraph(company, ss["CIHTitle"]),
        Paragraph(subtitle, ss["CIHSub"]),
    ]


def _styled_table(data: list[list], col_widths: list[float] | None = None) -> Table:
    t = Table(data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT]),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D5DCEA")),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    return t


# --------------------------------------------------------------------------- #
# PDF: single project
# --------------------------------------------------------------------------- #
def project_pdf(project: dict, company: str = "Construction Intelligence Hub",
                currency: str = "INR") -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=18 * mm,
                            title=f"Project Report - {project.get('name')}")
    ss = _styles()
    story = _header_block(company, f"Project Report — {project.get('name', '')}", ss)

    story.append(Paragraph("Project Overview", ss["CIHH2"]))
    overview = [
        ["Field", "Value"],
        ["Project name", project.get("name") or "-"],
        ["Client", project.get("client") or "-"],
        ["Location", project.get("location") or "-"],
        ["Building type", project.get("building_type") or "-"],
        ["Floors", str(project.get("floors") or "-")],
        ["Built-up area", f"{format_number(project.get('area_sqft'), 0)} sqft"],
        ["Status", project.get("status") or "-"],
        ["Progress", f"{project.get('progress') or 0}%"],
        ["Start date", project.get("start_date") or "-"],
        ["Expected completion", project.get("end_date") or "-"],
        ["Budget", format_currency(project.get("budget"), currency)],
    ]
    story.append(_styled_table(overview, col_widths=[55 * mm, 115 * mm]))

    if project.get("notes"):
        story.append(Paragraph("Notes", ss["CIHH2"]))
        story.append(Paragraph(project["notes"], ss["Normal"]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# PDF: projects summary
# --------------------------------------------------------------------------- #
def projects_summary_pdf(projects: Iterable[dict],
                         company: str = "Construction Intelligence Hub",
                         currency: str = "INR") -> bytes:
    projects = list(projects)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=12 * mm, rightMargin=12 * mm,
                            topMargin=15 * mm, bottomMargin=18 * mm,
                            title="Projects Summary")
    ss = _styles()
    story = _header_block(company, "Projects Summary Report", ss)

    total_budget = sum(float(p.get("budget") or 0) for p in projects)
    story.append(Paragraph(
        f"Total projects: <b>{len(projects)}</b> &nbsp;•&nbsp; "
        f"Total budget: <b>{format_currency(total_budget, currency)}</b>",
        ss["Normal"],
    ))
    story.append(Spacer(1, 8))

    data = [["#", "Name", "Client", "Type", "Status", "Floors", "Area (sqft)", "Budget"]]
    for p in projects:
        data.append([
            str(p.get("id")),
            p.get("name") or "-",
            p.get("client") or "-",
            p.get("building_type") or "-",
            p.get("status") or "-",
            str(p.get("floors") or "-"),
            format_number(p.get("area_sqft"), 0),
            format_currency(p.get("budget"), currency),
        ])
    story.append(_styled_table(
        data,
        col_widths=[10 * mm, 42 * mm, 30 * mm, 22 * mm, 22 * mm, 15 * mm, 20 * mm, 25 * mm],
    ))
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# PDF: material estimation
# --------------------------------------------------------------------------- #
def estimation_pdf(inputs: dict, quantities: dict, costs: dict,
                   company: str = "Construction Intelligence Hub",
                   currency: str = "INR",
                   project_name: str | None = None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=18 * mm,
                            title="Material Estimation Report")
    ss = _styles()
    subtitle = "Material Estimation Report"
    if project_name:
        subtitle += f" — {project_name}"
    story = _header_block(company, subtitle, ss)

    story.append(Paragraph("Inputs", ss["CIHH2"]))
    story.append(_styled_table([
        ["Parameter", "Value"],
        ["Length (m)", format_number(inputs.get("length"))],
        ["Width (m)", format_number(inputs.get("width"))],
        ["Height (m)", format_number(inputs.get("height"))],
        ["Floors", str(inputs.get("floors"))],
        ["Quality", inputs.get("quality") or "-"],
    ], col_widths=[55 * mm, 115 * mm]))

    story.append(Paragraph("Materials & Cost Breakdown", ss["CIHH2"]))
    rows = [["Material", "Quantity", "Rate", "Cost"]]
    for line in costs["lines"].values():
        rows.append([
            line["label"],
            format_number(line["quantity"]),
            format_currency(line["rate"], currency),
            format_currency(line["cost"], currency),
        ])
    rows.append(["", "", "Subtotal", format_currency(costs["subtotal"], currency)])
    rows.append(["", "", f"Tax ({costs['tax_percent']}%)", format_currency(costs["tax_amount"], currency)])
    rows.append(["", "", "TOTAL", format_currency(costs["total"], currency)])

    tbl = _styled_table(rows, col_widths=[70 * mm, 30 * mm, 35 * mm, 35 * mm])
    tbl.setStyle(TableStyle([
        ("FONTNAME", (2, -1), (-1, -1), "Helvetica-Bold"),
        ("BACKGROUND", (2, -1), (-1, -1), ACCENT),
        ("TEXTCOLOR", (2, -1), (-1, -1), colors.white),
    ]))
    story.append(tbl)
    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()


# --------------------------------------------------------------------------- #
# Excel writers
# --------------------------------------------------------------------------- #
def _style_header(ws, ncols: int) -> None:
    fill = PatternFill(start_color="1E4FD8", end_color="1E4FD8", fill_type="solid")
    font = Font(bold=True, color="FFFFFF")
    for col in range(1, ncols + 1):
        cell = ws.cell(row=1, column=col)
        cell.fill = fill
        cell.font = font
        cell.alignment = Alignment(horizontal="center", vertical="center")


def projects_summary_excel(projects: Iterable[dict], currency: str = "INR") -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Projects"
    headers = ["ID", "Name", "Client", "Location", "Type", "Floors",
               "Area (sqft)", "Budget", "Status", "Progress %",
               "Start Date", "End Date", "Notes"]
    ws.append(headers)
    _style_header(ws, len(headers))
    for p in projects:
        ws.append([
            p.get("id"), p.get("name"), p.get("client"), p.get("location"),
            p.get("building_type"), p.get("floors"), p.get("area_sqft"),
            p.get("budget"), p.get("status"), p.get("progress"),
            p.get("start_date"), p.get("end_date"), p.get("notes"),
        ])
    for col_idx, _ in enumerate(headers, start=1):
        ws.column_dimensions[chr(64 + col_idx)].width = 18
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def project_excel(project: dict, currency: str = "INR") -> bytes:
    wb = Workbook()
    ws = wb.active
    ws.title = "Project"
    ws.append(["Field", "Value"])
    _style_header(ws, 2)
    for k, v in project.items():
        ws.append([k, v])
    ws.column_dimensions["A"].width = 22
    ws.column_dimensions["B"].width = 50
    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def estimation_excel(inputs: dict, quantities: dict, costs: dict,
                     currency: str = "INR") -> bytes:
    wb = Workbook()

    ws1 = wb.active
    ws1.title = "Inputs"
    ws1.append(["Parameter", "Value"])
    _style_header(ws1, 2)
    for k, v in inputs.items():
        ws1.append([k, v])
    ws1.column_dimensions["A"].width = 20
    ws1.column_dimensions["B"].width = 20

    ws2 = wb.create_sheet("Materials & Cost")
    ws2.append(["Material", "Quantity", "Rate", "Cost"])
    _style_header(ws2, 4)
    for line in costs["lines"].values():
        ws2.append([line["label"], line["quantity"], line["rate"], line["cost"]])
    ws2.append([])
    ws2.append(["", "", "Subtotal", costs["subtotal"]])
    ws2.append(["", "", f"Tax ({costs['tax_percent']}%)", costs["tax_amount"]])
    ws2.append(["", "", "TOTAL", costs["total"]])
    for col, w in zip("ABCD", (32, 14, 14, 16)):
        ws2.column_dimensions[col].width = w

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()


def budget_summary_pdf(projects: Iterable[dict],
                       company: str = "Construction Intelligence Hub",
                       currency: str = "INR") -> bytes:
    projects = list(projects)
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=15 * mm, rightMargin=15 * mm,
                            topMargin=15 * mm, bottomMargin=18 * mm,
                            title="Budget Summary")
    ss = _styles()
    story = _header_block(company, "Budget Summary Report", ss)
    by_status: dict[str, float] = {}
    by_type: dict[str, float] = {}
    total = 0.0
    for p in projects:
        b = float(p.get("budget") or 0)
        total += b
        by_status[p.get("status") or "Unknown"] = by_status.get(p.get("status") or "Unknown", 0) + b
        by_type[p.get("building_type") or "Unknown"] = by_type.get(p.get("building_type") or "Unknown", 0) + b

    story.append(Paragraph(f"Grand total budget: <b>{format_currency(total, currency)}</b>", ss["Normal"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Budget by status", ss["CIHH2"]))
    data = [["Status", "Total Budget"]] + [
        [k, format_currency(v, currency)] for k, v in by_status.items()
    ]
    story.append(_styled_table(data, col_widths=[80 * mm, 80 * mm]))

    story.append(Paragraph("Budget by building type", ss["CIHH2"]))
    data = [["Building Type", "Total Budget"]] + [
        [k, format_currency(v, currency)] for k, v in by_type.items()
    ]
    story.append(_styled_table(data, col_widths=[80 * mm, 80 * mm]))

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    return buf.getvalue()
